<div class="row">
    <div class="col-md-6">
        <form name="contact-form" action="/contact" method="post">

            <div class="form-group">
                <label for="email">Your E-mail</label>
                <input name="email" type="text" class="form-control"
                placeholder="name@example.com">
            </div>

            <br>
            <div class="form-group"> 
                <label for="subject">Subject</label>
                <input name="subject" type="text" class="form-control"
                placeholder="Type subject here">
            </div>

            <br>
            <div class="form-group"> 
                <label for="body">Message</label>
                <textarea name="body" class="form-control" rows="6"
                 placeholder="What would you want us to know"></textarea>
            </div>
            
            <fieldset>
<!--                <legend>Choose a payment method:</legend>-->
                <input type="radio" name="payment" value="paypal">PayPal</input>
                <input type="radio" name="payment" value="card">Credit Card</input>
            </fieldset>
            <br>
            <input name="submit" type="submit" value="Submit">
        </form>
    </div>
</div>