<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('GTFD'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
 <?php echo $this->headScript()
            ->prependFile($this->basePath() . '../js/bootstrap.min.js')
            ->prependFile($this->basePath() . '../js/photo-gallery.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/site.css')
              
        
        ?>

        <!-- Scripts -->

    </head>
    <body>
        <nav>
        <div class="container"> 
			<img class="logo" src="../images/logo.png" alt="GTFD" />
		<img class="menu-icon" src="../images/menu-icon.png" alt="Click to expand menu" />
			<ul class="nav-list"> 
			 <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>	
			
                         <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                      <li><a href="<?php echo $this->url('about/ourstory') ?>">Our Story</a></li>
                                    <li><a href="<?php echo $this->url('about/history') ?>">History</a></li>
                                    <li><a href="<?php echo $this->url('about/vision') ?>">Vision</a></li>
                                    <li><a href="<?php echo $this->url('about/goals') ?>">Goals</a></li>
                                    <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                </ul>
                            </li>
                             <li><a href="<?php echo $this->url('resource') ?>"><?php echo $this->translate('Resources') ?></a></li>	
                             <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
                              <li class="active"><a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a></li>
                        <li><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
                        </ul>
	
			<ul class="social-list">
				<li><a href="#" target="_blank"><img src="../images/twitter.png" alt="Twitter" /></a></li>
				<li><a href="https://www.facebook.com/GTFDProject?fref=ts" target="_blank"><img src="../images/facebook.png" alt="Facebook" /></a></li>
				<li><a href="#"><img src="../images/linkdin.png" alt="Linkdin" /></a></li>
				<li><a href="https://instagram.com/give_a_teen_a_future_dream/" target="_blank"><img src="../images/instagram.png" alt="Instagram" /></a></li>
				<li><a href="#" target="_blank"><img src="../images/google.png" alt="Google+" /></a></li>
			</ul>
		</div>
	</nav>
        <div class="container">
	<header>
	<h1>Gallery</h1>
	<h3>Our first group of individuals  were the talented kids at the Lentegeur High school </h3>
	</header>
	 <ul class="row">
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (30).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (50).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (60).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (8).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (10).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (17).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (26).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (2).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (11).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (13).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (12).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (22).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (21).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (4).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (5).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (24).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (7).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (19).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (9).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (1).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (90).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (70).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (76).jpg">
            </li>
            <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                <img class="img-responsive" src="images/GTFD/gtfd (86).jpg">
            </li>
          </ul>             
    </div> <!-- /container -->
	 <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">         
          <div class="modal-body">                
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
	</body>
	<footer>
		<div class="container ">
			<div class="col-one-third">
			<h3>About</h3>
				<dl class="footer-list">
                                    <dt><a href="<?php echo $this->url('about/ourstory') ?>">Our Story</dt></a>
				<dd><!--on March 10, 2014--></dd>
				<dt><a href="<?php echo $this->url('about/mission') ?>">Mission</dt></a>
				<dd><!--on March 10, 2014--></dd>
				<dt><a href="<?php echo $this->url('about/vision') ?>">Vision</dt></a>
				<dd><!--on March 10, 2014--></dd>
				<dt><a href="<?php echo $this->url('about/goals') ?>">Goals</dt></a>
				<dd><!--on March 10, 2014--></dd>
                                
				</dl>
			
			</div>
			<div class="col-one-third">
				<h3>Contact Us</h3>
				<address>7 Lentegeur Road<br/>
				Mitchells Plain 
				<br/>7785<br/><br/>
				+27 81 598 1610<br/><br/>
				<a href=""mailto:danyaal@gtfd.co.za>danyaal@gtfd.co.za</a>
				</address>
			</div>
			<div class="col-one-third registration">
				
				<h3>Memorable Moments</h3>
				<div id="slideshow">
   <div>
     <img src="/images/GTFD/gtfd (25).jpg" width="200px" height="150px">
   </div>
   <div>
    <img src="/images/GTFD/gtfd (23).jpg" width="200px" height="150px">
   </div>
   <div>
    <img src="/images/GTFD/gtfd (45).jpg" width="200px" height="150px">
   </div>
</div>
			 </div>
			 <div style="clear:both;"></div>
			</div><!-- Container -->
			<span class="copyright">&copy;copyright 2014, GTFD</span>
	 </footer>
	 
	 <script>
		$(function() {
			$nav = $('.nav-list');
			
			$('.menu-icon').click(function() {
				$nav.slideToggle();			
			});
			
			$(window).resize(function(){
				if ($(window).width() >= 640){
					$nav.show();
				}else {
					$nav.hide();
				}
			
			});
		});
		
	 </script>
<script> $("#slideshow > div:gt(0)").hide();

setInterval(function() { 
  $('#slideshow > div:first')
    .fadeOut(1000)
    .next()
    .fadeIn(1000)
    .end()
    .appendTo('#slideshow');
},  3000);</script>
	 
	
</html>