<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('GTFD'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/site.css')
        
        ?>

        <!-- Scripts -->

    </head>
    <body>
        <nav>
        <div class="container"> 
			<img class="logo" src="../images/logo.png" alt="GTFD" />
		<img class="menu-icon" src="../images/menu-icon.png" alt="Click to expand menu" />
			<ul class="nav-list"> 
			 <li ><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>	
			
                         <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">

                                    About <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                         <li><a href="<?php echo $this->url('about/ourstory') ?>">Our Story</a></li>
                                    <li><a href="<?php echo $this->url('about/history') ?>">History</a></li>
                                    <li><a href="<?php echo $this->url('about/vision') ?>">Vision</a></li>
                                    <li><a href="<?php echo $this->url('about/goals') ?>">Goals</a></li>
                                    <li><a href="<?php echo $this->url('about/mission') ?>">Mission</a></li>
                                </ul>
                            </li>
                             <li class="active"><a href="<?php echo $this->url('resource') ?>"><?php echo $this->translate('Resources') ?></a></li>	
                             <li><a href="<?php echo $this->url('events') ?>"><?php echo $this->translate('Events') ?></a></li>
                              <li><a href="<?php echo $this->url('gallery') ?>"><?php echo $this->translate('Gallery') ?></a></li>
                       <li><a href="<?php echo $this->url('register') ?>"><?php echo $this->translate('Register') ?></a></li>
                        </ul>
	
			<ul class="social-list">
				<li><a href="#" target="_blank"><img src="../images/twitter.png" alt="Twitter" /></a></li>
				<li><a href="https://www.facebook.com/GTFDProject?fref=ts" target="_blank"><img src="../images/facebook.png" alt="Facebook" /></a></li>
				<li><a href="#"><img src="../images/linkdin.png" alt="Linkdin" /></a></li>
				<li><a href="https://instagram.com/give_a_teen_a_future_dream/" target="_blank"><img src="../images/instagram.png" alt="Instagram" /></a></li>
				<li><a href="#" target="_blank"><img src="../images/google.png" alt="Google+" /></a></li>
			</ul>
		</div>
	</nav>
        <header class="container">
		<h1>Resources</h1>
		<h3>Helping young teens get ahead of the curve</h3>
                <h5>We have compiled multiple PDF containing all papers and memos for the subjects below</h5>
		
	
            
            <ul class="pdf text-center">
                
                <div class="col-md-4"><img src="../images/Accounting.png" alt="Twitter" /><li><br><a href="../pdf/Accounting/AccountingPackage(AFR).pdf" target="_blank" />Accounting Afrikaans Package</a></li><br>
                    <li><a href="../pdf/Accounting/AccountingPackage(Eng).pdf" target="_blank" />Accounting English Package</a></li><br></div>
                
                
                <div class="col-md-4"><img src="../images/language.png" alt="Twitter" /><li><br><a href="../pdf/Afrikaans/Afrikaans HL P1-P3.pdf" target="_blank" />Afrikaan HL P1-P3</a></li><br>
                <li><a href="../pdf/Afrikaans/Afrikaans FAL P1-P3.pdf" target="_blank" />Afrikaans FAL P1-P3</a></li><br></div>
                
                <div class="col-md-4"><img src="../images/civil tech.png" alt="Twitter" /><li><br><a href="../pdf/Civil Technology/CivilTechnologyPackage(Afr).pdf" target="_blank" />Civil Technology Afrikaans Package</a></li><br>
                <li><a href="../pdf/Civil Technology/CivilTechnologyPackage(Eng).pdf" target="_blank" />Civil Technology English Package</a></li><br>
                </div>
           
               <div class="col-md-4"><img src="../images/language.png" alt="Twitter" /><br><li><a href="../pdf/English/English HL P1-P3.pdf" target="_blank" />English HL P1-P3</a></li><br>
                <li><a href="../pdf/English/English FAL P1-P3.pdf" target="_blank" />English FAL P1-P3</a></li><br></div>
                
                <div class="col-md-4"><img src="../images/geography.png" alt="Twitter" /> <br> <li><a href="../pdf/Geography/GeographyPackage(AFR).pdf" target="_blank" />Geography Afrikaans Package</a></li><br>
                <li><a href="../pdf/Geography/GeographyPackage(Eng).pdf" target="_blank" />Geography English Package</a></li><br></div>
                
                <div class="col-md-4"><img src="../images/history.png" alt="Twitter" /><br><li><a href="../pdf/History/HistoryPackage(Afr).pdf" target="_blank" />History Afrikaans Package</a></li><br>
                <li><a href="../pdf/History/HistoryPackage(Eng).pdf" target="_blank" />History English Package</a></li><br></div>
                

                <div class="col-md-4"><img src="../images/biology.png" alt="Twitter" /><br><li><a href="../pdf/Life Science/LifeSciencePackage(Afr).pdf" target="_blank" />Life Science Afrikaans Package</a></li><br>
                <li><a href="../pdf/Life Science/LifeSciencePackage(Eng).pdf" target="_blank" />Life Science English Package</a></li><br></div>
                
                <div class="col-md-4"><img src="../images/maths.png" alt="Twitter" /><br><li><a href="../pdf/Maths/MathematicsPackage(Afr).pdf" target="_blank" />Mathematics Afrikaans Package</a></li><br>
                <li><a href="../pdf/Maths/MathematicsPackage(Eng).pdf" target="_blank" />Mathematics English Package</a></li><br></div>
                
                <div class="col-md-4"><img src="../images/maths.png" alt="Twitter" /> <br>  <li><a href="../pdf/Maths Lit/MathsLitPackage(Afr).pdf" target="_blank" />Mathematics Literacy Afrikaans Package</a></li><br>
                <li><a href="../pdf/Maths Lit/MathsLitPackage(Eng).pdf" target="_blank" />Mathematics Literacy English Package</a></li><br></div>
                
                
                
                
                
             
                
               
                <div class="col-md-4"  id="pdf"><img src="../images/Science.png" alt="Twitter" /><br> <li><a href="../pdf/Physcial Science/PhysicalSciencePackage(Afr).pdf" target="_blank" />Physical Science Afrikaans Package</a></li><br>
                <li><a href="../pdf/Physcial Science/PhysicalSciencePackage(Eng).pdf" target="_blank" />Physical Science English Package</a></li><br></div>
                <div class="col-md-4" id="pdf"><img src="../images/tourism.png" alt="Twitter" /> <br><li><a href="../pdf/Tourism/TourismPackage(Afr).pdf" target="_blank" />Tourism Afrikaans Package</a></li><br>
                <li><a href="../pdf/Tourism/TourismPackage(Eng).pdf" target="_blank" />Tourism English Package</a></li><br></div>
                <div class="col-md-4"><img class="pic" src="../images/tourism.png" alt="Twitter" visiabilty="hidden"/></div>
                
                
              
                
               
		<!--<div class="col-md-4"><img src="../images/tourism.png" alt="Twitter" /></div>	-->
			</ul>
            
                </header>
	<footer>
		<div class="container ">
			<div class="col-one-third">
				<h3>About</h3>
				<dl class="footer-list">
                                    <dt><a href="<?php echo $this->url('about/ourstory') ?>">Our Story</dt></a>
				<dd><!--on March 10, 2014--></dd>
				<dt><a href="<?php echo $this->url('about/mission') ?>">Mission</dt></a>
				<dd><!--on March 10, 2014--></dd>
				<dt><a href="<?php echo $this->url('about/vision') ?>">Vision</dt></a>
				<dd><!--on March 10, 2014--></dd>
				<dt><a href="<?php echo $this->url('about/goals') ?>">Goals</dt></a>
				<dd><!--on March 10, 2014--></dd>
                                
				</dl>
			
			</div>
			<div class="col-one-third">
				<h3>Contact Us</h3>
				<address>7 Lentegeur Road<br/>
				Mitchells Plain 
				<br/>7785<br/><br/>
				+27 81 598 1610<br/><br/>
				<a href=""mailto:danyaal@gtfd.co.za>danyaal@gtfd.co.za</a>
				</address>
			</div>
			<div class="col-one-third registration">
				<h3>Memorable Moments</h3>
				<div id="slideshow">
   <div>
     <img src="/images/GTFD/gtfd (17).jpg" width="200px" height="150px">
   </div>
   <div>
    <img src="/images/GTFD/gtfd (67).jpg" width="200px" height="150px">
   </div>
   <div>
    <img src="/images/GTFD/gtfd (31).jpg" width="200px" height="150px">
   </div>
   <div>
    <img src="/images/GTFD/gtfd (41).jpg" width="200px" height="150px">
   </div>
</div>
			 </div>
			 <div style="clear:both;"></div>
			</div><!-- Container -->
			<span class="copyright">&copy;copyright 2014, GTFD</span>
	 </footer>
	 
	 <script>
		$(function() {
			$nav = $('.nav-list');
			
			$('.menu-icon').click(function() {
				$nav.slideToggle();			
			});
			
			$(window).resize(function(){
				if ($(window).width() >= 640){
					$nav.show();
				}else {
					$nav.hide();
				}
			
			});
		});
	 </script>
	 <script> $("#slideshow > div:gt(0)").hide();

setInterval(function() { 
  $('#slideshow > div:first')
    .fadeOut(1000)
    .next()
    .fadeIn(1000)
    .end()
    .appendTo('#slideshow');
},  3000);</script>
	</body>
</html>